name: Synchronization
on:
  push:
    branches: 
      - main
jobs:
  synchronizing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Continuous Integration
        run: |
          docker build . -t dcondoris950/my_api_vm:latest
          docker login -u dcondoris950 -p testvm1234
          docker push dcondoris950/my_api_vm:latest
      - name: Continuous Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u dcondoris950 -p testvm1234
            docker container stop test_vm
            docker container rm test_vm
            docker pull dcondoris950/my_api_vm:latest 
            docker run --name test_vm -d -p 8000:8000 dcondoris950/my_api_vm:latest 