name: Synchronization
on:
  push:
    branches: 
      - main
jobs:
  synchronizing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Continuous Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: XX.XX.XX.XX
          username: ubuntu
          password: 
          port: 22
          script: |
            docker pull
            docker-compose up # --no-cache